# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: linkyard_development
  pool: 5
  username: linkyard_pg
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: linkyard_test
  pool: 5
  username: linkyard_pg
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: linkyard
  pool: 5
  username: linkyard_pg
  password:

cucumber:
  <<: *TEST
